version: "3.9"
services:
  stampy:
    stop_signal: SIGKILL # won't respond to anything else
    build:
      dockerfile: ./Dockerfile
    volumes:
      - "./local:/stampydata"
    environment:
      - "FACTOID_DATABASE_PATH=/stampydata/Factoids.db"
