name: stampy
channels:
  - defaults
dependencies:
  - pip
  - numpy
  - sqlite
  - pip:
    - openai
    - black
    - discord-py
    - google-api-python-client
    - google-auth-oauthlib
    - python-dotenv
    - gitpython

