name: stampy
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pip
  - sqlite
  - pip:
    - black
    - discord-py
    - gitpython
    - google-api-python-client
    - google-auth-oauthlib
    - openai
    - psutil
    - python-dotenv

