# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Jinja2" = super.buildPythonPackage rec {
    pname = "Jinja2";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl";
      sha256 = "0q9a30x046p3wvbgx598g4lmxwwykk0vjsjl21khx7r3zq5r7230";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/7c/59a3248f411813f8ccba92a55feaac4bf360d29e2ff05ee7d8e1ef2d7dbf/MarkupSafe-2.1.3.tar.gz";
      sha256 = "1bfwpdm04zswg5lgw1kvc67sp95ib0wpi0kvfhdnzs3a5p9qwndg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Werkzeug" = super.buildPythonPackage rec {
    pname = "Werkzeug";
    version = "2.3.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/d6/8040faecaba2feb84e1647af174b3243c9b90c163c7ea407820839931efe/Werkzeug-2.3.6-py3-none-any.whl";
      sha256 = "14483bcy9k45a6a715n01w665v92hivq0j5jjn8vpbqk2kx3jmck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "aiohttp" = super.buildPythonPackage rec {
    pname = "aiohttp";
    version = "3.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/fd/1ff4da09ca29d8933fda3f3514980357e25419ce5e0f689041edb8f17dab/aiohttp-3.8.4.tar.gz";
      sha256 = "0p5bj6g7ca19gvwk8fz00k579ma9w9kd27ssh2zl3r61ca8ilbmz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiosignal"
      self."async-timeout"
      self."attrs"
      self."charset-normalizer"
      self."frozenlist"
      self."multidict"
      self."yarl"
    ];
  };
  "aiosignal" = super.buildPythonPackage rec {
    pname = "aiosignal";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl";
      sha256 = "05rvv06k1460w8jcgsv6qsm82zvbnf0frkag9rc6ms6ignq6ydzq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."frozenlist"
    ];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "4.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl";
      sha256 = "0g1v719nh6l516d6f7cq3j2zbz9cwhbf99ficqyl21qdypyf98cc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "19.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl";
      sha256 = "073xrfixypmvlimyfj4733bz9f9c9yi63ywsnm7f8x1s3ij6ra88";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "black" = super.buildPythonPackage rec {
    pname = "black";
    version = "23.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/36/66370f5017b100225ec4950a60caeef60201a10080da57ddb24124453fba/black-23.3.0.tar.gz";
      sha256 = "0h69vald94pd5hk9kqrhyryfi574fx32dmyb3km432kjdrh8syqw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."mypy-extensions"
      self."packaging"
      self."pathspec"
      self."platformdirs"
      self."tomli"
      self."typing-extensions"
    ];
  };
  "blinker" = super.buildPythonPackage rec {
    pname = "blinker";
    version = "1.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/f1/5f39e771cd730d347539bb74c6d496737b9d5f0a53bc9fdbf3e170f1ee48/blinker-1.6.2-py3-none-any.whl";
      sha256 = "1w5i3brxcl3g9wiii83dqzarlg92hk12wpxz1a3c4yxv59vkkmy3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cachetools" = super.buildPythonPackage rec {
    pname = "cachetools";
    version = "5.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/c9/c8a7710f2cedcb1db9224fdd4d8307c9e48cbddc46c18b515fefc0f1abbe/cachetools-5.3.1-py3-none-any.whl";
      sha256 = "1415235xqp2ywmp8g7krjshc7ak3ckrkfr7h6qpbl57ax8g67vwm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2023.5.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/19/59961b522e6757f0c9097e4493fa906031b95b3ebe9360b2c3083561a6b4/certifi-2023.5.7-py3-none-any.whl";
      sha256 = "05n7h0lz1vh69hqlqi0vkygm74fx539gw5l93z5fysbqbj7ykhn6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/d7/8d757f8bd45be079d76309248845a04f09619a7b17d6dfc8c9ff6433cac2/charset-normalizer-3.1.0.tar.gz";
      sha256 = "1d89yl32j0c6i25zip73h5nq55jyxf2vyqxfg9crbsvhqgws5q1l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl";
      sha256 = "0j6vn6ayxq1bqs1v64r90sarg05hj6rxj4w29vs0k9hmrcrq2kdv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "codaio" = super.buildPythonPackage rec {
    pname = "codaio";
    version = "0.6.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/02/d8/37aa87109390e555cacf2a9a1e5df91ee03a281fc2d67148f46516909534/codaio-0.6.10-py3-none-any.whl";
      sha256 = "1h6k8385ynmavnpjl386d3pgy4crkd084k16cfmnx5h02hgrjhwp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."decorator"
      self."envparse"
      self."inflection"
      self."python-dateutil"
      self."requests"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl";
      sha256 = "0q7p11gj5g158gb1igy9cna5ppxf03zkrm2gpr4acjycl3159yj1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "discord-py" = super.buildPythonPackage rec {
    pname = "discord-py";
    version = "2.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/78/241e04365a7dd8456f9b9e7db60c6e672a154d6683831aba03c3cda62756/discord.py-2.3.1-py3-none-any.whl";
      sha256 = "039qidl03c6mc5679054yg5g237qzk10735zf1i716d29pr555hl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohttp"
    ];
  };
  "envparse" = super.buildPythonPackage rec {
    pname = "envparse";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/8d/bee8a59732c169a455627ff1557d0db180f7c352b0274480267ad3e46875/envparse-0.2.0.tar.gz";
      sha256 = "1dvf0m2jc49s3150b6hwi644apn0zq3g1bdl9q97zljmpckrlfsg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "filelock" = super.buildPythonPackage rec {
    pname = "filelock";
    version = "3.12.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/45/ec3407adf6f6b5bf867a4462b2b0af27597a26bd3cd6e2534cb6ab029938/filelock-3.12.2-py3-none-any.whl";
      sha256 = "1v6i0rvrl1397djhw47hkqg1c38amdlm4nxclqyz4wiaxb6r3dyb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "flask" = super.buildPythonPackage rec {
    pname = "flask";
    version = "2.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/1a/f191d32818e5cd985bdd3f47a6e4f525e2db1ce5e8150045ca0c31813686/Flask-2.3.2-py3-none-any.whl";
      sha256 = "1c3hjq7aw5bipfkw3jky8vjhdvbwfimj61s9wcyr5jfq9494xzbp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Jinja2"
      self."Werkzeug"
      self."blinker"
      self."click"
      self."importlib-metadata"
      self."itsdangerous"
    ];
  };
  "frozenlist" = super.buildPythonPackage rec {
    pname = "frozenlist";
    version = "1.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/10/d629476346112b85c912527b9080944fd2c39a816c2225413dbc0bb6fcc0/frozenlist-1.3.3.tar.gz";
      sha256 = "0sispcpras096fxrd0i35qs25fqy4r0x8v1d6f40pag845bwbg2q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fsspec" = super.buildPythonPackage rec {
    pname = "fsspec";
    version = "2023.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/bd/4c0a4619494188a9db5d77e2100ab7d544a42e76b2447869d8e124e981d8/fsspec-2023.6.0-py3-none-any.whl";
      sha256 = "16l65hsrqm0mr5wcwrwibh047gywbfdsw1f0dnx1yf9yxzxd3fhw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gitdb" = super.buildPythonPackage rec {
    pname = "gitdb";
    version = "4.0.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/a6/35f83efec687615c711fe0a09b67e58f6d1254db27b1013119de46f450bd/gitdb-4.0.10-py3-none-any.whl";
      sha256 = "1iqmhkr94m2zx40hg9jvy6dkwzwysfly9acnxmwl01i6hhlwz1n2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap"
    ];
  };
  "gitpython" = super.buildPythonPackage rec {
    pname = "gitpython";
    version = "3.1.31";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/8a/d1e02cc111d65b0346f70abb83c51f8593e7134bf694a4a56d1a470caaf7/GitPython-3.1.31-py3-none-any.whl";
      sha256 = "13dyinwxxq7gnrgfzl6d0cqn7vq3fjlydqdv1jk179va9xhr6j7h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."gitdb"
    ];
  };
  "google-api-core" = super.buildPythonPackage rec {
    pname = "google-api-core";
    version = "2.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/c4/c3cd048b6cbeba8d9ae50dd7643ac065b85237338aa7501b0efae91eb4d9/google_api_core-2.11.1-py3-none-any.whl";
      sha256 = "0jp9gb6fi7bzhnnydblkkw2jnhqfm4l5brg4kr5lzp9nvj95lanr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."googleapis-common-protos"
      self."protobuf"
      self."requests"
    ];
  };
  "google-api-python-client" = super.buildPythonPackage rec {
    pname = "google-api-python-client";
    version = "2.91.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/d1/7e0e2148e027e8781c115b30003825cd3e92aa48b86dd40e42acd34f3a7d/google_api_python_client-2.91.0-py2.py3-none-any.whl";
      sha256 = "1clsbwx6wgmf505xfwkz7s7w0bx0m2vafb36d5fgdh109cfx4nb9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-api-core"
      self."google-auth"
      self."google-auth-httplib2"
      self."httplib2"
      self."uritemplate"
    ];
  };
  "google-auth" = super.buildPythonPackage rec {
    pname = "google-auth";
    version = "2.21.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/77/4737ca3b929e95df9234827f7ddcf66199df2d96057ba9a98168957de7fa/google_auth-2.21.0-py2.py3-none-any.whl";
      sha256 = "0s0jn6v6cifr0wdprbw7r64n3ap3rvw9m6yrc5q5l3zsfk81hgys";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cachetools"
      self."pyasn1-modules"
      self."rsa"
      self."six"
      self."urllib3"
    ];
  };
  "google-auth-httplib2" = super.buildPythonPackage rec {
    pname = "google-auth-httplib2";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/db/721e2f3f32339080153995d16e46edc3a7657251f167ddcb9327e632783b/google_auth_httplib2-0.1.0-py2.py3-none-any.whl";
      sha256 = "042a3yfgl0ic4mksyqysz4nisghy08zcn5r6x1bknr5mqqv9rr1i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."httplib2"
      self."six"
    ];
  };
  "google-auth-oauthlib" = super.buildPythonPackage rec {
    pname = "google-auth-oauthlib";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/07/8d9a8186e6768b55dfffeb57c719bc03770cf8a970a074616ae6f9e26a57/google_auth_oauthlib-1.0.0-py2.py3-none-any.whl";
      sha256 = "1yym7xwhyljs8ihxnjbfbf1n452vrxq1fk8r907k134j0jkhr24m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."google-auth"
      self."requests-oauthlib"
    ];
  };
  "googleapis-common-protos" = super.buildPythonPackage rec {
    pname = "googleapis-common-protos";
    version = "1.59.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/b7/bbaa556e9ff0580f408c64ccf4db0c1414eec79e7151d33a10bc209ffb6d/googleapis_common_protos-1.59.1-py2.py3-none-any.whl";
      sha256 = "07m64hrdn5bcwlx0cm8cgmz70xq769b85i5livhhf74gnrpxpghc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."protobuf"
    ];
  };
  "helicone" = super.buildPythonPackage rec {
    pname = "helicone";
    version = "0.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9b/54/d4a1b87270b1dce8499e504a13a5059843faaba2425219904c2f0c60ebc9/helicone-0.1.3-py3-none-any.whl";
      sha256 = "0ysf7dalwj2xww893vad4x8rhg2szajig9frxrs7pni6xzp4wc0w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."openai"
    ];
  };
  "httplib2" = super.buildPythonPackage rec {
    pname = "httplib2";
    version = "0.22.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/6c/d2fbdaaa5959339d53ba38e94c123e4e84b8fbc4b84beb0e70d7c1608486/httplib2-0.22.0-py3-none-any.whl";
      sha256 = "1p34vl4v0j39aifl1fimyj09kyxhmdzg6z72x4vkv3xsq59hmbhl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
    ];
  };
  "huggingface-hub" = super.buildPythonPackage rec {
    pname = "huggingface-hub";
    version = "0.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/a2/8a416d167216403ceeef3aaf8c22b0c61b1ae571644473d67eb7fecbb69e/huggingface_hub-0.15.1-py3-none-any.whl";
      sha256 = "0i9lz2id7hm0mjppn71pqid25zj962n4hil6xvgjbxpipc5gpc05";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."filelock"
      self."fsspec"
      self."packaging"
      self."pyyaml"
      self."requests"
      self."tqdm"
      self."typing-extensions"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl";
      sha256 = "1hn54ps4kgv2fmyvfaks38sgrvjc1cn4834sh7gadsx3x9wpxdwh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "6.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/94/64287b38c7de4c90683630338cf28f129decbba0a44f0c6db35a873c73c4/importlib_metadata-6.7.0-py3-none-any.whl";
      sha256 = "1dg532flm41hhdbiizq7mbiiss6qjzg7j7n7vb2sz5wyclp0hlnb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "inflection" = super.buildPythonPackage rec {
    pname = "inflection";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/35/a6eb45b4e2356fe688b21570864d4aa0d0a880ce387defe9c589112077f8/inflection-0.3.1.tar.gz";
      sha256 = "1jhnxgnw8y3mbzjssixh6qkc7a3afc4fygajhqrqalnilyvpzshq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "itsdangerous" = super.buildPythonPackage rec {
    pname = "itsdangerous";
    version = "2.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/5f/447e04e828f47465eeab35b5d408b7ebaaaee207f48b7136c5a7267a30ae/itsdangerous-2.1.2-py3-none-any.whl";
      sha256 = "0i6vi2yb1a0qjc311bdpgj40h21c09sv1dnlv2cqdf2i4c8lj8rc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jellyfish" = super.buildPythonPackage rec {
    pname = "jellyfish";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8e/14/d72e01b3e3d5d9f1f5f12c8afafda88f068385c612d8aa517df2b88e2059/jellyfish-1.0.0.tar.gz";
      sha256 = "1m0vi2crjp2jnq6wqfhj7qpq8zna55pnj9qcwmyb16wrf4vaw6l8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/5a/e11cad7b79f2cf3dd2ff8f81fa8ca667e7591d3d8451768589996b65dec1/lxml-4.9.2.tar.gz";
      sha256 = "0rsvhd03cv7fczd04xqf1idlnkvjy0hixx2p6a5k6w5cnypcym94";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/15/bd620f7a6eb9aa5112c4ef93e7031bcd071e0611763d8e17706ef8ba65e0/multidict-6.0.4.tar.gz";
      sha256 = "0jfsq7dnaja8jnd4ih02fhp6ic2ryhn7zfg7q19n9dzgj9j90rin";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mypy-extensions" = super.buildPythonPackage rec {
    pname = "mypy-extensions";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl";
      sha256 = "0bam8jwfajm34qnwrd9jzp6fj2qglzznil93ksk6hmlaxg0gd4j3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "1.25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/b2/fe774844d1857804cc884bba67bec38f649c99d0dc1ee7cbbf1da601357c/numpy-1.25.0.tar.gz";
      sha256 = "06gzvwv81srw1jdlmm7dyjsx3q4xysn8dplidajcvhwdlblwmb7i";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "oauthlib" = super.buildPythonPackage rec {
    pname = "oauthlib";
    version = "3.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/80/cab10959dc1faead58dc8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl";
      sha256 = "1jpvcxq0xr3z50fdg828in1icgz8cfcy3sc04r85vqhkmjdg4fc1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "openai" = super.buildPythonPackage rec {
    pname = "openai";
    version = "0.27.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/78/7588a047e458cb8075a4089d721d7af5e143ff85a2388d4a28c530be0494/openai-0.27.8-py3-none-any.whl";
      sha256 = "0g70jziw74kh3ap1fylc8pa4pwx2h95nsg5hai9vxg96vbvw59z0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohttp"
      self."requests"
      self."tqdm"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "23.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl";
      sha256 = "0qfwgvgx5f74cqlzjjlpzslw21wxc9jgcsxz5vmc80lm8apr6iwr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pandas" = super.buildPythonPackage rec {
    pname = "pandas";
    version = "2.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/a7/824332581e258b5aa4f3763ecb2a797e5f9a54269044ba2e50ac19936b32/pandas-2.0.3.tar.gz";
      sha256 = "0g04w897b9r0835lnz3ahy77ihfgfd668fh9scv7zlg0i0m3fby0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
      self."python-dateutil"
      self."pytz"
      self."tzdata"
    ];
  };
  "pathspec" = super.buildPythonPackage rec {
    pname = "pathspec";
    version = "0.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/c8/551a803a6ebb174ec1c124e68b449b98a0961f0b737def601e3c1fbb4cfd/pathspec-0.11.1-py3-none-any.whl";
      sha256 = "14sj9al5230sxwhxgkgdj5yysincl7lb68jc2fym89b5fspp1byq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "platformdirs" = super.buildPythonPackage rec {
    pname = "platformdirs";
    version = "3.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/61/7fde5beff25a0dae6c2056203696169bd29188b6cedefff8ba6e7b54417b/platformdirs-3.8.0-py3-none-any.whl";
      sha256 = "0bnazipzz66xdsnks71zdcc4wv7ajcy3vcljw1rblxihwy6dk7na";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "protobuf" = super.buildPythonPackage rec {
    pname = "protobuf";
    version = "4.23.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/9d/20e9bf4067e85c3074f1f5bac820a3cfb9ce885cddd8a649fe3570659c77/protobuf-4.23.3.tar.gz";
      sha256 = "0jz37zxhdikv6i0c8jgmsyhcimrzsd0dpgmdrm92lcq00srvx4ks";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "5.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/0f/96b7309212a926c1448366e9ce69b081ea79d63265bde33f11cc9cfc2c07/psutil-5.9.5.tar.gz";
      sha256 = "0g7bcssmy7pmg88gbh5bc1nqxkca0h1wwlgwazcm977k9n76642l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1" = super.buildPythonPackage rec {
    pname = "pyasn1";
    version = "0.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/e5/b56a725cbde139aa960c26a1a3ca4d4af437282e20b5314ee6a3501e7dfc/pyasn1-0.5.0-py2.py3-none-any.whl";
      sha256 = "0mqss25alxjzl76blcs383k7xy8gd03ivbxwr9c97b51888158l7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyasn1-modules" = super.buildPythonPackage rec {
    pname = "pyasn1-modules";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/8e/bea464350e1b8c6ed0da3a312659cb648804a08af6cacc6435867f74f8bd/pyasn1_modules-0.3.0-py2.py3-none-any.whl";
      sha256 = "0b8n9ac70q1kywc3hc699drx0i5xxy8bs25y2v3zp7qd8znxdk6k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/24/6ae4c9c45cf99d96b06b5d99e25526c060303171fb0aea9da2bfd7dbde93/pyparsing-3.1.0-py3-none-any.whl";
      sha256 = "1h86zdkdf6b78avbvibamm1hbn4zq5dlh11i33vxlgbx39nsjm6m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl";
      sha256 = "1aaxjfp4lrz8c6qls3vdhw554lan3khy9afyvdcvrssk6kf067cn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/2f/62ea1c8b593f4e093cc1a7768f0d46112107e790c3e478532329e434f00b/python_dotenv-1.0.0-py3-none-any.whl";
      sha256 = "0ahj14q5i66vs60skgfyx16xdw53wn4qrhzj9c50f0dp4s91m5zm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2023.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/99/ad6bd37e748257dd70d6f85d916cafe79c0b0f5e2e95b11f7fbc82bf3110/pytz-2023.3-py2.py3-none-any.whl";
      sha256 = "1yxzpfzld6zvavc0zfk83qq0xa72gprlv0d96i71vnlfp2mv6ld1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "regex" = super.buildPythonPackage rec {
    pname = "regex";
    version = "2023.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/df/401fd39ffd50062ff1e0344f95f8e2c141de4fd1eca1677d2f29609e5389/regex-2023.6.3.tar.gz";
      sha256 = "1c7yrgk4pa0p5q792igvilk6aj462gz7llavng75083dydds5lbj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.31.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl";
      sha256 = "0gq02gh497vhifc00hvz1gpg5absfx8sgg05cpifcw0yq23j3kaq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "requests-oauthlib" = super.buildPythonPackage rec {
    pname = "requests-oauthlib";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/bb/5deac77a9af870143c684ab46a7934038a53eb4aa975bc0687ed6ca2c610/requests_oauthlib-1.3.1-py2.py3-none-any.whl";
      sha256 = "1dfspmj87kr7nc1d22aqy7z0dhs7dq6hk7f00jihb3gvl80waxr5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."oauthlib"
      self."requests"
    ];
  };
  "rsa" = super.buildPythonPackage rec {
    pname = "rsa";
    version = "4.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/97/fa78e3d2f65c02c8e1268b9aba606569fe97f6c8f7c2d74394553347c145/rsa-4.9-py3-none-any.whl";
      sha256 = "1xvlc59ipksbkz746bkxibnpwwm8bzvhwk9lcxlph575b280s9lh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyasn1"
    ];
  };
  "safetensors" = super.buildPythonPackage rec {
    pname = "safetensors";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/54/44496d0eb0c1cd415d76bff20c38c6e0a07346e69ee532027738891a4940/safetensors-0.3.1.tar.gz";
      sha256 = "0sg8s0n0qk9c97ykdsqgy776vlwqv8f64fwjajpcignhz1psa7ap";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "slack-sdk" = super.buildPythonPackage rec {
    pname = "slack-sdk";
    version = "3.21.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/f5/7071b22e77918bebb2e6729bd273fa1f2cc70be3a2bb089bc60f2ea2d8c1/slack_sdk-3.21.3-py2.py3-none-any.whl";
      sha256 = "1k5r7f8g6y204hk1srlgyg4796dwkzs6dib8rmhhp53r4jwhfg6y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/01/7caa71608bc29952ae09b0be63a539e50d2484bc37747797a66a60679856/smmap-5.0.0-py3-none-any.whl";
      sha256 = "150d3676rvpfb44wwmcf3pbrxc07cblmfp6y165qvrs0l3b1kfia";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "structlog" = super.buildPythonPackage rec {
    pname = "structlog";
    version = "23.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0c/b2/0c0951c78f3f59ce44e93cb9b2140d305a00bb8262532041c702d4d4300a/structlog-23.1.0-py3-none-any.whl";
      sha256 = "03ky1xfw0xg470qy4pdk0mxgirj4g52glc7184s3fkmm927fdfbr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tokenizers" = super.buildPythonPackage rec {
    pname = "tokenizers";
    version = "0.13.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/9c/936ebad6dd963616189d6362f4c2c03a0314cf2a221ba15e48dd714d29cf/tokenizers-0.13.3.tar.gz";
      sha256 = "0bmgflm8dj374qpsayvd38qks4mhzcvk2da2aj5008xnd2xnsm1f";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tqdm" = super.buildPythonPackage rec {
    pname = "tqdm";
    version = "4.65.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/02/a2cff6306177ae6bc73bc0665065de51dfb3b9db7373e122e2735faf0d97/tqdm-4.65.0-py3-none-any.whl";
      sha256 = "0wcnkv4ysw5a61p2w71qp7hzzs0vccic1vmwba0k5q9pzqbkmxf4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "transformers" = super.buildPythonPackage rec {
    pname = "transformers";
    version = "4.30.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/0b/e45d26ccd28568013523e04f325432ea88a442b4e3020b757cf4361f0120/transformers-4.30.2-py3-none-any.whl";
      sha256 = "079zq4kd46dampbw52vv4c01r4rm28jh7d2nwnfdi7kz16iy6cn3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."filelock"
      self."huggingface-hub"
      self."numpy"
      self."packaging"
      self."pyyaml"
      self."regex"
      self."requests"
      self."safetensors"
      self."tokenizers"
      self."tqdm"
    ];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl";
      sha256 = "0djba5hpzzc96yjdra5i2lxvrfmhd76vqczl9cbn1c4kmz9ms3a4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tzdata" = super.buildPythonPackage rec {
    pname = "tzdata";
    version = "2023.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/fb/a79efcab32b8a1f1ddca7f35109a50e4a80d42ac1c9187ab46522b2407d7/tzdata-2023.3-py2.py3-none-any.whl";
      sha256 = "1nhya5q3qmnzwdwy3wnnwzhxqynv8rarp4xnk503281ixwz7crby";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "uritemplate" = super.buildPythonPackage rec {
    pname = "uritemplate";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c0/7461b49cd25aeece13766f02ee576d1db528f1c37ce69aee300e075b485b/uritemplate-4.1.1-py2.py3-none-any.whl";
      sha256 = "0bp08jq51nrjha3sgfc4dwk3d2cflfa5kl7alhp33pcvv6w0h343";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/05/c214b32d21c0b465506f95c4f28ccbcba15022e000b043b72b3df7728471/urllib3-1.26.16-py2.py3-none-any.whl";
      sha256 = "03z2vi0y2qp0g12h46g5mriz8n1yn6iv84c4c0abg2kdc6ksydld";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "yarl" = super.buildPythonPackage rec {
    pname = "yarl";
    version = "1.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/3f/04b3c5e57844fb9c034b09c5cb6d2b43de5d64a093c30529fd233e16cf09/yarl-1.9.2.tar.gz";
      sha256 = "0w9mh8851i7chig0vab5djcxyz5p2y9zxay207c0cz2qkx5rvaq4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."multidict"
    ];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/fa/c9e82bbe1af6266adf08afb563905eb87cab83fde00a0a08963510621047/zipp-3.15.0-py3-none-any.whl";
      sha256 = "0mnmg9nwhrbnb55i7d1ssi7c79f14rbxkphs2npl5rb0db3lz428";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
