name: Deploy to Development Server
on:
  push:
    branches: [master, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stampy to Development Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_DEV_HOST}}
          key: ${{secrets.SSH_DEV_KEY}}
          username: ${{secrets.SSH_DEV_USERNAME}}
          script: |
            source /root/.zshrc
            source /root/stampy/scripts/update-stampy.sh