name: Deploy to Production Server
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stampy to Production Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_PROD_HOST}}
          key: ${{secrets.SSH_PROD_KEY}}
          username: ${{secrets.SSH_PROD_USERNAME}}
          port: ${{secrets.SSH_PROD_PORT}}
          script: |
            source ~/.bashrc
            source ~/stampy/scripts/update-stampy.sh
