name: Deploy to PRODelopment Server
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stampy to Production Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_PROD_HOST}}
          key: ${{secrets.SSH_PROD_KEY}}
          username: ${{secrets.SSH_PROD_USERNAME}}
          script: |
            pkill -f stam.py
            cd /home/rob/stampy
            python3 -m scripts.notify-discord-stampy-offline
            git pull
            conda env remove -n stampy
            conda env create -f environment.yml
            conda activate stampy
