name: Deploy to Development Server
on:
  push:
    branches: [master, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stampy to Development Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_DEV_HOST}}
          key: ${{secrets.SSH_DEV_KEY}}
          username: ${{secrets.SSH_DEV_USERNAME}}
          script: |
            pkill -f stam.py
            pkill -f runstampy
            cd ~/stampy
            conda activate stampy
            python -m scripts.notify-discord-stampy-offline
            git pull
            conda deactivate
            conda env remove -n stampy
            conda env create -f environment.yml
            conda activate stampy
            ./runstampy > ~/"stampy-log-$(date +"%F-%T")" 2>&1 &
            conda deactivate