name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: stampy
          environment-file: environment.yml
          auto-activate-base: false
        run: python3 -m unittest